config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/home', to: 'pages#home', as: :home
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :items do
    resources :reservations, only: [:new, :create, :index, :show]
    collection do
      get 'myreservations', to: 'reservations#my_reservations'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_one_attached :picture

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 6 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
    against: %i[name category],
    using: {
    tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :start_date, :end_date, :total_price, presence: true
  validate :end_date_after_start_date

  before_validation :set_total_price

  def total_days
    (end_date - start_date).to_i + 1
  end

  private

  def set_total_price
    self.total_price = item.price.to_f * total_days
  end

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date <= start_date
      errors.add(:end_date, "doit être après la date de début")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :reservations

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    if params[:query].present?
      @items = Item.search_by_name_and_category(params[:query])
      @markers = @items.geocoded.map do |item|
        {
          lat: item.latitude,
          lng: item.longitude
        }
      end
      render 'search_results'
    else
      @items = Item.all
      render 'index'
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :description, :picture, :address, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_item, only: %i[create new]

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.item = @item
    @reservation.user = current_user
    if @reservation.save!
      redirect_to item_reservation_path(@item, @reservation), notice: 'Réservation confirmée.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def my_reservations
    @reservations = current_user.reservations.includes(:item)
  end

  def index
    @items = Item.all
    @reservations = Reservation.includes(:user, :item).all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<div class="row justify-content-center">
<div class="col-4">
  <h1 class="my-4 text-center">Ajouter votre produit </h1>
    <%= simple_form_for(@item) do |f| %>
      <div class="mb-3" ><%= f.input :category, collection: ["Jardinage", "Outils", "Mobilier", "Sports & Loisirs", "Cuisine", "Électroménager", "Accessoires"], label: "Catégorie" %></div>
      <div class="mb-3"><%= f.input :name, label: "Nom du produit" %></div>
      <div class="mb-3"><%= f.input :picture, as: :file, label: "Télécharger une image" %></div>
      <div class="mb-3"><%= f.input :price, label: "prix" %></div>
      <div class="mb-3"><%= f.input :address, label: "Adresse" %></div>
      <div class="mb-3"> <%= f.input :description, label: "Description" %></div>
      <div class="text-center"><%= f.button :submit, "Mettre à jour", class: "btn btn-primary" %></div>
    <% end %>
       <div class="text-center mt-3">
    <%= link_to "Retour", items_path, class: "btn btn-secondary"%>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container mt-2 mb-2">
  <h1 class="index-title text-center">Location de matériel entre voisins</h1>
  </div>
  <div class="row mx-5">
    <% @items.each do |item| %>
      <div class="col-md-3 mb-3">
        <div class="items-card card shadow bg-white text-dark h-100">
        <% if item.user == current_user %>
          <div class="red-plain-circle"></div>
        <% else %>
          <div class="green-plain-circle"></div>
        <% end %>

            <div class="image-container">
              <% if item.picture.key.nil? %>
                <%= image_tag "logo.jpg", class: 'card-img-top' %>
              <% else %>
                <%= cl_image_tag item.picture.key, alt: "Items", class: 'card-img-top' %>
              <% end %>
            </div>

            <div class="card-body mt-2">
                <h5 class="card-title"><%= item.name %></h5>
            <h6 class="card-item-cat text-muted"><%= item.category %></h6>
          </div>
          <div class="card-footer">
            <div class= "mb-3">
              <%= link_to "détails", item_path(item), class: 'btn btn-info text-white detail-button' %>
            </div>
              <p class="card-text"><strong><%= item.price %> € / jour</strong></p>
            <div class="blockquote-footer">
              <p><%= item.address %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="row justify-content-center">
<div class="col-4">
  <h1 class="my-4 text-center">Ajouter votre produit </h1>
    <%= simple_form_for(@item) do |f| %>
      <div class="mb-3" ><%= f.input :category, collection: ["Jardinage", "Outils", "mobilier", "sports & loisirs", "cuisine", "électro-ménager", "accessoires"], label: "Catégorie" %></div>
      <div class="mb-3"><%= f.input :name, label: "Nom du produit" %></div>
      <div class="mb-3"><%= f.input :picture, as: :file, label: "Télécharger une image" %></div>
      <div class="mb-3"><%= f.input :price, label: "Prix" %></div>
      <div class="mb-3"><%= f.input :address, label: "Adresse" %></div>
      <div class="mb-3"> <%= f.input :description, label: "Description" %></div>
      <i>* mention obligatoire</i>
      <div class="text-center"><%= f.button :submit, "Ajouter", class: "btn btn-success b-button valid-button" %></div>
    <% end %>

       <div class="text-center mt-3 mb-4">
    <%= link_to "Retour", items_path, class: "btn btn-outline-success back-button" %>
    </div>
  </div>
</div>

app/views/items/search_results.html.erb
<div class="container">
  <h1 class="text-center mb-5">Résultats de la recherche</h1>
  <div class="row">
    <div class="col-md-6">
      <% @items.each do |item| %>
        <div class="items-card-search card shadow bg-white text-dark mb-3">
          <div class="image-container">
            <% if item.picture.key.nil? %>
              <%= image_tag "logo.jpg", class: 'card-img-top' %>
            <% else %>
              <%= cl_image_tag item.picture.key, alt: "Items", class: 'card-img-top' %>
            <% end %>
          </div>
          <div class="card-body mt-2">
            <% if item.user == current_user %>
              <h5 class="card-title"><strong>Votre</strong> <%= item.name %></h5>
            <% else %>
              <h5 class="card-title"><%= item.name %> <strong>À louer</strong></h5>
            <% end %>
            <h6 class="card-item-cat text-muted"><%= item.category %></h6>
          </div>
          <div class="card-footer">
            <div class="mb-3">
              <%= link_to "détails", item_path(item), class: 'btn btn-info' %>
            </div>
            <p class="card-text"><strong><%= item.price %> € / jour</strong></p>
            <div class="blockquote-footer">
              <p><%= item.address %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div id="map-container">
          <div style="width: 100%; height: 600px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
          </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
<div class="element position-relative" style="top: -20px">
<%= link_to('<i class="fa-solid fa-arrow-left back-arrow"></i>'.html_safe, "/items".html_safe) %>

</div>

  <%# Titre de l'item %>
  <h2> <%= @item.name %></h2>
  <p class="adress"><%= @item.address %></p>

<%# cartes photos de l'item %>
<div class="cards">
<%# image 1 from form %>
    <div class="card-category">
      <% if @item.picture.attached? %>
        <%= image_tag url_for(@item.picture), class: 'card-img-top' %>
      <% else %>
        <%= image_tag "logo.jpg", class: 'card-img-top' %>
      <% end %>
    </div>
<%# image 2 from unsplash %>
<div class="card-category">
<% translated_item = DeepL.translate "#{@item.name}", 'FR', 'EN' %>
    <%= image_tag "https://source.unsplash.com/random/?#{translated_item}", class: 'card-img-top' %>
  </div>
<%# image 3 from unsplash %>
<div class="card-category">
    <%= image_tag "https://source.unsplash.com/random/?#{translated_item}s", class: 'card-img-top' %>
  </div>
</div>

  <%# description/category à gauche - price/bouton à droite %>
  <div class="description-price">
    <div class="left-side">
      <p class="category">Category : <%= @item.category %></p>
      <p class="description">Description : <%= @item.description %></p>
    </div>
    <div class="right-side">
      <p class="price"><%= number_to_currency(@item.price, unit: "€", format: "%n %u / jour") %></p>
        <% if %>
        <% @item.user == current_user %>
          <%= link_to "Mettre à jour", edit_item_path, class: "btn btn-reserve valid-button" %>
          <%= link_to "Supprimer", item_path(@item), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sur(e)s"} %>
        <% else %>
          <%= link_to "Réserver", new_item_reservation_path(@item), class: "btn btn-reserve valid-button" %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoisinApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-3 mb-3">
  <h1 class=" text-center mt-3">Location de matériel divers entre voisins</h1>
</div>
<div>
  <h2 class=" text-start mx-5 mb-5">Inspirations</h2>
</div>

  <div class="main-pictures rounded mx-5">
    <div class="row justify-content-around my-3 rounded">
      <div class="col-3 text-center">
        <%= image_tag 'four_pizza.jpg', alt: 'accueil1', class: ' img-home mb-3' %>
        <h5>Four à pizza Ooni</h5>
        <p>Location à la journée</p>
      </div>
      <div class="col-3 text-center">
        <%= image_tag 'tronconneuse.jpg', alt: 'accueil2', class: ' img-home mb-3' %>
        <h5>Tronçonneuse Bosch</h5>
        <p>Location à l'heure / journée</p>
      </div>
      <div class="col-3 text-center">
        <%= image_tag 'pergola.jpg', alt: 'accueil3', class: ' img-home mb-3' %>
        <h5>Tonnelle de jardin</h5>
        <p>Location à la journée</p>
      </div>
      <div class="col-3 text-center">
        <%= image_tag 'tondeuse.jpg', alt: 'accueil4', class: ' img-home mb-3' %>
        <h5>Tondeuse Husqvarna</h5>
        <p>Location à l'heure / journée</p>
      </div>
    </div>
  </div>

  <div class="text-center ">
    <%= link_to 'Découvrir', items_path, class: 'btn btn-danger m-4 mb-5' %>
  </div>

  <div class="row mb-3">
    <div id="carouselExampleDark" class="carousel carousel-dark slide col-8 mx-auto">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="2000">
          <div class="carousel-image">
            <%= image_tag 'batteur_electrique.jpg', class: 'd-block w-100', alt: 'batteur' %>
            <div class="carousel-caption d-none d-md-block">
              <h5>Batteur Électrique</h5>
              <p>Préparez vos recettes facilement avec ce batteur.</p>
            </div>
          </div>
        </div>
        <div class="carousel-item" data-bs-interval="10000">
          <div class="carousel-image">
            <%= image_tag 'barbe_papa.jpg', class: 'd-block w-100', alt: 'barbe_papa' %>
            <div class="carousel-caption d-none d-md-block">
              <h5>Machine à barbe à Papa</h5>
              <p>Idéale pour les anniversaires</p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="carousel-image">
            <%= image_tag 'marteau.jpg', class: 'd-block w-100', alt: 'marteau' %>
            <div class="carousel-caption d-none d-md-block">
              <h5>Marteau</h5>
              <p>Un outil indispensable pour tous vos travaux.</p>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="d-flex justify-content-center align-items-center min-vh-100 bg-white">
    <div class="text-center">
        <h1 class="mb-4">Nous vous remercions pour votre reservation</h1>
        <p>Votre reservation a été prise en compte et sera traitée dans les meilleurs délais. Vous recevrez un e-mail de confirmation de reservation.</p>
        <a href="/" class="btn btn-primary mt-3">Revenir à la page d'accueil</a>
    </div>
</div>
<div class="alert alert-primary" role="alert">
  Consultez vos e-mails !
</div>

app/views/reservations/my_reservations.html.erb
<div class="container mt-2 mb-2">
  <h1 class="index-title text-center">Voici l'ensemble des réservations en cours de validation</h1>
  </div>
  <div class="row mx-5">
    <% @reservations.each do |reservation| %>
      <div class="col-md-3 mb-3">
        <div class="items-card card shadow bg-white text-dark h-100">
            <div class="image-container">
              <% if reservation.item.picture.key.nil? %>
                <%= image_tag "logo.jpg", class: 'card-img-top' %>
              <% else %>
                <%= cl_image_tag reservation.item.picture.key, alt: "Items", class: 'card-img-top' %>
              <% end %>
            </div>

            <div class="card-body mt-2">
                <h5 class="card-title"><%= reservation.item.name %></h5>
            <h6 class="card-item-cat text-muted"><%= reservation.item.category %></h6>
            <h6>en cours de validation</h6>
            <%# <p class="card-text"><%= item.description </p> %>
          </div>
          <div class="card-footer">
            <div class= "mb-3">
            </div>
            <p class="card-text"><strong> <%= reservation.item.price  %> € </strong></p>
            <p>Client: <%= reservation.user.username %></p>
            <div class="blockquote-footer">
              <li> ID de réservation n°<%= reservation.id %></li>
              <li>ID de l'objet n° <%= reservation.item.id %></li>
              <li>ID de l'utilisateur n°<%= reservation.user.id %></li>
              <%= link_to "détails", item_reservation_path(reservation.item, reservation) %>


            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container mt-0" data-controller='flatpickr' data-flatpickr-price-value="<%= @item.price%>">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 mt-0 bt-0">
      <h2 class="text-center my-4">Vous souhaitez réserver cet article :</h2>
        <div class="row justify-content-center mt-3">
          <div class="card shadow-sm pb-0 col-8">
            <div class="card-body text-center py-1">
              <h3 class="card-title"><%= @item.name %></h3>
              <p class="mb-0 text-secondary"><%= number_to_currency(@item.price, unit: "€", format: "%n %u / jour") %></p>
            </div>
          </div>
        </div>
      <p class="text-center my-4">Merci de compléter les détails de votre réservation ici ⬇️</p>
      <div class="form-container text-center">
        <div class="row justify-content-center mt-3">
          <div class="reservation-card card shadow col-8">
            <div class="card-body">
              <div class="dates d-flex justify-content-center mb-3" data-controller="update-price">
                <%= simple_form_for [@item, @reservation] do |form| %>
                  <%= form.input :start_date, as: :string, input_html: { id: 'start-date', data: { flatpickr_date_format: "d-m-Y", flatpickr_min_date: Date.today, flatpickr_target: 'startDate' } } %>

                  <%= form.input :end_date, as: :string, input_html: { id: 'end-date', data: { flatpickr_date_format: "d-m-Y", flatpickr_min_date: Date.today, flatpickr_target: 'endDate' } } %>

                  <div class="form-group">
                    <p data-flatpickr-target="days">Nombre de jours total de location: 0</p>
                    <p data-flatpickr-target="totalPrice">Prix total de votre location: 0 €</p>
                  </div>
                </div>
                <%= link_to item_reservations_path(@item) do %>
                  <%= form.submit "Confirmer votre commande" %>
                <% end %>
                <%= "Vous ne serez pas directement prélevé(e)" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/reservations/show.html.erb
<h1>Voici le récapitulatif de votre réservation</h1>

<div>
  <div>
    <strong>Date de début:</strong>
    <%= @reservation.start_date.strftime("%d/%m/%Y") %>
  </div>
  <div>
    <strong>Date de fin:</strong>
    <%= @reservation.end_date.strftime("%d/%m/%Y") %>
  </div>
  <div>
    <strong>Prix journalier:</strong>
    <%= @reservation.item.price %> €
  </div>
  <div>
    <strong>Durée total:</strong>
    <%= (@reservation.end_date - @reservation.start_date).to_i %> Jours
  </div>
  <div>
    <strong>Votre total:</strong>
    <%= @reservation.total_price %> €
  </div>


<style>
  .reservation-summary {
    border: 1px solid #ccc;
    padding: 20px;
    margin-top: 20px;
  }

  .reserve-button {
    background-color: red;
    color: white;
    border: none;
    padding: 10px 20px;
    cursor: pointer;
  }

  .reserve-button:hover {
    background-color: darkred;
  }
</style>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to home_path, class: "navbar-brand" do %>
    <div class="navbar-brand">
        <%= image_tag "logo-app.png" %>
    </div>
    <% end %>
    <div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <form class="d-flex mx-auto" role="search" action="<%= items_path %>">
        <div class="search-container ">
          <input class="form-control me-2 rounded-5 opacity-50 search-bar" type="search" name="query" placeholder="votre recherche" aria-label="Search">
          <button class="btn search-bar-button" type="submit no-hover"><i class="fa-solid fa-magnifying-glass"></i></button>
        </div>
      </form>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active searchbar mt-2">
        <%= link_to "Ajouter un produit", new_item_path, class: "nav-link mx-5" %>
        </li>
        <li class="nav-item">
          <%# <%= link_to "My reservation", reservations_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to "#", class: "nav-link dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" } do %>
            <%= image_tag "small_logo.png", alt: "Menu", class: "avatar" %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if current_user == nil %>
              <%= link_to "Connexion", new_user_session_path, class: "dropdown-item" %>
            <% else %>
              <p class="username-login text-center"><%= current_user.username %></p>
              <%= link_to "Déconnexion",  destroy_user_session_path, class: "dropdown-item text-center", data: {turbo_method: :delete} %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>